FROM node:12-alpine as build

WORKDIR /usr/src/app

COPY dist/site package.json ./

RUN npm install --production

FROM nginx:1.19.6-alpine

COPY --from=build /usr/src/app /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]